//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int Id { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string fname { get; set; }
        public string Mname { get; set; }
        public string Lname { get; set; }
        public string Address { get; set; }
        public string MobileH { get; set; }
        public string MobileF { get; set; }
        public string MobileP { get; set; }
        public string Email { get; set; }
        public Nullable<int> AreId { get; set; }
        public string QualificationId { get; set; }
        public Nullable<int> StreamId { get; set; }
        public Nullable<int> OccupationId { get; set; }
        public string CourseId { get; set; }
        public string SchoolName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PreferTimeTO { get; set; }
        public string PreferTimeFrom { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> TotalFees { get; set; }
        public Nullable<int> DisCount { get; set; }
        public Nullable<decimal> NetFees { get; set; }
        public Nullable<int> NoOfInstallment { get; set; }
        public Nullable<decimal> Installment1Rs { get; set; }
        public Nullable<System.DateTime> Installment1Date { get; set; }
        public Nullable<decimal> Installment2Rs { get; set; }
        public Nullable<System.DateTime> Installment2Date { get; set; }
        public Nullable<decimal> Installment3Rs { get; set; }
        public Nullable<System.DateTime> Installment3Date { get; set; }
        public Nullable<decimal> Installment4Rs { get; set; }
        public Nullable<System.DateTime> Installment4Date { get; set; }
        public Nullable<decimal> Installment5Rs { get; set; }
        public Nullable<System.DateTime> Installment5Date { get; set; }
        public Nullable<decimal> Installment6Rs { get; set; }
        public Nullable<System.DateTime> Installment6Date { get; set; }
        public Nullable<decimal> Installment7Rs { get; set; }
        public Nullable<System.DateTime> Installment7Date { get; set; }
        public Nullable<decimal> Installment8Rs { get; set; }
        public Nullable<System.DateTime> Installment8Date { get; set; }
        public Nullable<decimal> Installment9Rs { get; set; }
        public Nullable<System.DateTime> Installment9Date { get; set; }
        public Nullable<decimal> Installment10Rs { get; set; }
        public Nullable<System.DateTime> Installment10Date { get; set; }
        public Nullable<System.DateTime> EntDt { get; set; }
        public Nullable<int> EntBy { get; set; }
        public Nullable<System.DateTime> ModDt { get; set; }
        public Nullable<int> ModBy { get; set; }
        public string AdmissionNo { get; set; }
        public Nullable<bool> isdelete { get; set; }
        public string RegNo { get; set; }
    }
}
