//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int Id { get; set; }
        public int CountyId { get; set; }
        public string StataName { get; set; }
    }
}
