//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExam
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int ExamId { get; set; }
        public bool IsExamFinish { get; set; }
        public System.DateTime EntDt { get; set; }
        public int EntBy { get; set; }
        public System.DateTime ModDt { get; set; }
        public int ModBy { get; set; }
    }
}
